[window]
padding = { x = 4, y = 4 }
startup_mode = "Maximized"

[font]
normal = { family  = "AdwaitaMono Nerd Font" }
size = 10.5

[colors.normal]
blue = '#54546D'

[cursor]
thickness = 0.2

[terminal]
shell = { program = "ubuntu.exe" }
